import type { AgentManifest, Run, RunEvent, RunInput } from '@agentage/core';

/** Machine info — sent by daemon on registration */
export interface Machine {
  /** Unique machine ID (generated by daemon on first run, persisted locally) */
  id: string;

  /** Human-readable name (hostname or user-provided) */
  name: string;

  /** OS platform */
  platform: 'darwin' | 'win32' | 'linux';

  /** CPU architecture */
  arch: 'x64' | 'arm64';

  /** Daemon version */
  daemonVersion: string;

  /** Agent manifests discovered on this machine (from factories) */
  agents: AgentManifest[];

  /** Online status (derived from heartbeat — set by hub, not daemon) */
  status: 'online' | 'offline';

  /** Last heartbeat timestamp (Unix ms, set by hub) */
  lastSeenAt: number;
}

/** Heartbeat payload — sent by daemon periodically */
export interface Heartbeat {
  machineId: string;

  /** Updated agent list (in case agents changed since last heartbeat) */
  agents: AgentManifest[];

  /** Currently active run IDs on this machine */
  activeRunIds: string[];

  /** Machine resource snapshot (optional) */
  resources?: {
    cpuUsage?: number;
    memoryUsedMb?: number;
    memoryTotalMb?: number;
    diskUsedMb?: number;
    diskTotalMb?: number;
  };

  /** Daemon-configured default install target for agents (agents.default) */
  agentsDefault?: string;

  /** Daemon-configured default discovery root for projects (projects.default) */
  projectsDefault?: string;
}

/** Agent as seen from the hub — manifest + which machine it's on */
export interface AgentInfo extends AgentManifest {
  machineId: string;
  machineName: string;
  machineStatus: 'online' | 'offline';
}

// ─── Protocol — REST ──────────────────────────────────────────

export interface MachineRegisterRequest {
  machine: Omit<Machine, 'status' | 'lastSeenAt'>;
  authToken: string;
}

export interface MachineRegisterResponse {
  machineId: string;
  /** Token for WebSocket connection */
  connectionToken: string;
}

export type HeartbeatRequest = Heartbeat;

export interface HeartbeatResponse {
  /** Pending commands for this machine */
  pendingCommands: Command[];
}

// ─── Command ──────────────────────────────────────────────────

export interface Command {
  id: string;
  type: 'cancel' | 'input';
  runId: string;
  /** Input text for 'input' type */
  payload?: string;
}

// ─── Protocol — WebSocket ─────────────────────────────────────

/** Execute an agent on this machine (hub → daemon) */
export interface WsExecuteRequest {
  type: 'execute';
  requestId: string;
  agentName: string;
  input: RunInput;
}

/** Cancel a running execution (hub → daemon) */
export interface WsCancel {
  type: 'cancel';
  runId: string;
}

/** Send input to a waiting agent (hub → daemon) */
export interface WsSendInput {
  type: 'input';
  runId: string;
  text: string;
}

/** Execution accepted — run created (daemon → hub) */
export interface WsExecuteAccepted {
  type: 'execute_accepted';
  requestId: string;
  runId: string;
}

/** Execution rejected — agent not found, busy, etc. (daemon → hub) */
export interface WsExecuteRejected {
  type: 'execute_rejected';
  requestId: string;
  reason: string;
}

/** Run event — streamed during execution (daemon → hub) */
export interface WsRunEvent {
  type: 'run_event';
  runId: string;
  event: RunEvent;
}

/** Run state changed — full run record (daemon → hub) */
export interface WsRunStateChange {
  type: 'run_state';
  run: Run;
}

// ─── Union types ──────────────────────────────────────────────

export type WsHubMessage = WsExecuteRequest | WsCancel | WsSendInput;
export type WsDaemonMessage = WsExecuteAccepted | WsExecuteRejected | WsRunEvent | WsRunStateChange;
export type WsMessage = WsHubMessage | WsDaemonMessage;
